In [2]:
import torch
import numpy as np

In [3]:
a = torch.FloatTensor(3,2)

In [5]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
v1 = torch.tensor([1.0, 1.0], requires_grad=True)
v2 = torch.tensor([2.0, 2.0])
v_sum = v1 + v2
v_res = (v_sum*2).sum()

In [18]:
v1.is_leaf, v2.is_leaf, v_sum.is_leaf, v_res.is_leaf

(True, True, False, False)

In [19]:
v1.requires_grad, v2.requires_grad, v_sum.requires_grad, v_res.requires_grad

(True, False, True, True)

In [20]:
v_res.backward()

In [21]:
v1.grad

tensor([2., 2.])

In [22]:
import torch.nn as nn

In [31]:
l = nn.Linear(2,5)

In [34]:
v = torch.FloatTensor([1,2])
l(v)

tensor([ 1.2187, -0.5451,  1.2201, -0.8456,  1.1595], grad_fn=<AddBackward0>)

In [35]:
v

tensor([1., 2.])